### ISSUE TITLE
The PhysActive column does not exist

### ISSUE THREAD

**Issue by lcnature** [poldrack/nhanes#2]
Hi @poldrack the textbook keeps mentioning a questionnaire about being physically active but it seems that I cannot find this column in the loaded dataset with the current version of the package. Not sure if it is because of some issue when grabbing the data from the website. 
I am trying to add an example to the notebook of the chapter on hypothesis testing to illustrate in class and that's why I encountered this issue.

**Comment by poldrack** [comment]
for those examples I had been using a variable called PhysActive which is present in the NHANES package for R.  However, it doesn't appear to be present in the data download from NHANES; I'm guessing that it was added by the package developer, unfortunately the links to the NHANES web site provided in the package help function don't exist any more.  

Here is the solution that I used to generate the python versions of the figures for the book, which uses rpy2 to load the R package:

https://github.com/statsthinking21/statsthinking21-figures-python/blob/main/src/03-SummarizingData.ipynb

**Comment by lcnature** [comment]
I see. I assume it is just an or operation of the columns `VigorousRecreationalActivity` and `ModerateRecreationalActivity`? Then I added a line to insert a new `PhysActive` column in my version of notebook and can make a pull request if you confirm this is correct.

**Comment by poldrack** [comment]
that seems reasonable.

**Comment by lcnature** [comment]
OK. Will do it!
